<?php

/**
 * @file
 * A custom client-side slideshow.
 */

/**
 * Implements hook_block_info().
 */
function custom_slideshow_block_info() {
  $blocks = array();
  
  $blocks['custom_slideshow'] = array(
    'info' => t('Custom Modules / Custom Slideshow'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function custom_slideshow_block_view($delta = '') {
  // Create an empty block.
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    
    case 'custom_slideshow':
      $block['subject'] = t('');
      $block['content'] = custom_slideshow();
      break;
    }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function custom_slideshow() {
  return theme('custom_slideshow', array()); 
}


/**
 * Implements hook_theme().
 */
function custom_slideshow_theme() {
  $module_path = drupal_get_path('module', 'custom_slideshow');
  $base = array(
    'path' => "$module_path/theme",
  );
  return array(
    'custom_slideshow' => $base + array(
      'template' => 'custom-slideshow-block',
    ),
  );
}

/**
 * Add javascript files for jquery slideshow.
 */
if (theme_get_setting('slideshow_js','simplecorp')):

	drupal_add_js(drupal_get_path('theme', 'simplecorp') . '/js/plugins/jquery.flexslider-min.js');

	//Initialize slideshow using theme settings
	$effect=theme_get_setting('slideshow_effect','simplecorp');
	$effect_time=theme_get_setting('slideshow_effect_time','simplecorp')*1000;
	$slideshow_controls=theme_get_setting('slideshow_controls','simplecorp');
	$slideshow_random=theme_get_setting('slideshow_random','simplecorp');
	$slideshow_pause=theme_get_setting('slideshow_pause','simplecorp');
	$slideshow_touch=theme_get_setting('slideshow_touch','simplecorp');

	drupal_add_js('
		jQuery(document).ready(function($) {

		    $(window).load(function() {

		        $(".flexslider").fadeIn("slow");

		        $(".flexslider").flexslider({
		            useCSS: false,
		            animation: "'.$effect.'",
		            controlNav: '.$slideshow_controls.',
		            directionNav: '.$slideshow_controls.',
		            animationLoop: true,
		            touch: '.$slideshow_touch.',
		            pauseOnHover: '.$slideshow_pause.',
		            nextText: "&rsaquo;",
		            prevText: "&lsaquo;",
		            keyboard: true,
		            slideshowSpeed: '.$effect_time.',
		            randomize: '.$slideshow_random.',
		            start: function(slider) {
		                slider.removeClass("loading");
		            }
		        });
		    });
		});',array('type' => 'inline', 'scope' => 'footer', 'weight' => 5)
	);

endif;