<?php

/**
 * @file
 * A custom client-side slideshow built for developers.
 */

/**
 * Implements hook_init().
 */
function custom_slideshow_init() {
  // Make the the theme call dynamic.
  $default_theme = variable_get('theme_default', 'simplecorp');
  
  /**
   * Add javascript files for the flexislider.
   */
  if (theme_get_setting('slideshow_js',$default_theme)) {
  
    drupal_add_js(drupal_get_path('module', 'custom_slideshow') . '/js/jquery.flexslider-min.js');
  
    //Initialize slideshow using theme settings
    
    //Initialize slideshow using theme settings
    $effect = theme_get_setting('slideshow_effect', $default_theme);
    $effect_time = theme_get_setting('slideshow_effect_time',$default_theme)*1000;
    $slideshow_controls = theme_get_setting('slideshow_controls',$default_theme);
    $slideshow_random = theme_get_setting('slideshow_random',$default_theme);
    $slideshow_pause = theme_get_setting('slideshow_pause',$default_theme);
    $slideshow_touch = theme_get_setting('slideshow_touch',$default_theme);
  
    // Pass the slideshow settings to Drupal.settings
    drupal_add_js(array(
      'custom_slideshow_array' => array(
        'effect' => $effect,
        'effect_time' => $effect_time,
        'slideshow_controls' => $slideshow_controls,
        'slideshow_random' => $slideshow_random,
        'slideshow_pause' => $slideshow_pause,
        'slideshow_touch' => $slideshow_touch
      )
    ), 'setting');

    drupal_add_js(drupal_get_path('module', 'custom_slideshow') . '/js/custom_slideshow.js');
 
  }  
}

/**
 * Implements hook_block_info().
 */
function custom_slideshow_block_info() {
  $blocks = array();
  
  $blocks['custom_slideshow'] = array(
    'info' => t('Custom Modules / Custom Slideshow'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function custom_slideshow_block_view($delta = '') {
  // Create an empty block.
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    
    case 'custom_slideshow':
      $block['subject'] = t('');
      $block['content'] = custom_slideshow();
      break;
    }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function custom_slideshow() {

  // Send custom_slideshow data objects to custom-slideshow-block.tpl.php which is registered below
  return theme('custom_slideshow', array(
    'keys' => array('u1','u2','u3'),
    // The original slideshow_images are 940 x 350 px
    'slideshow_image' => array('portfolio-pronq.jpg','portfolio-candd-msp.jpg', 'portfolio-candd-contenthub.jpg'),
    'alt_title' => array('img1','img2', 'img3'),
    'which_node' => array('node/7','node/6', 'node/5'),
    //'which_node' => array('pronq-hp','car-and-driver-model-super-page', 'car-and-driver-content-hub', 'car-and-drivers-menu-navigation', 'wealth-management-resource-network', 'industry-week-100-500-and-50-rankings', 'galavante-group', 'yoga-practice-manual'),
    'caption' => array('foo', 'bar', 'baz'),

  )); 
}
/**
 * Implements hook_theme().
 */
function custom_slideshow_theme() {
  $module_path = drupal_get_path('module', 'custom_slideshow');
  $base = array(
    'path' => "$module_path/theme",
  );
  return array(
    'custom_slideshow' => $base + array(
      'template' => 'custom-slideshow-block',
      'variables' => array(
        'keys' => NULL,
        'slideshow_image' => NULL,
        'alt_title' => NULL,
        'which_node' => NULL,
        'caption' => NULL,
      ),
    ),
  );
}
