<?php

/**
 * @file
 * A content block for the full portfolio.
 */

/**
 * Implements hook_block_info().
 */
function full_portfolio_block_info() {
  $blocks = array();
  
  $blocks['full_portfolio'] = array(
    'info' => t('Custom Modules / Full Portfolio'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function full_portfolio_block_view($delta = '') {
  // Create an empty block.
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    
    case 'full_portfolio':
      $block['subject'] = t('');
      $block['content'] = full_portfolio();
      break;
  }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function full_portfolio() {

  // Send full_portfolio data objects to full-portfolio-block.tpl.php which is registered below
  return theme('full_portfolio', array(
    'keys' => array('u1','u2','u3','u4','u5','u6','u7','u8','u9','u10'),
    'class_and_data_type' => array('web', 'web', 'web', 'web', 'web', 'web', 'web', 'illustration', 'illustration', 'illustration'),    
    'data_id' => array('id-211', 'id-128', 'id-209', 'id-215', 'id-39', 'id-213', 'id-281', 'id-280', 'id-282', 'id-283'),
    'portfolio_image' => array('portfolio-pronq.jpg','portfolio-candd-msp.jpg', 'portfolio-candd-contenthub.jpg', 'portfolio-candd-menu-nav.jpg', 'portfolio-wm-resource-network.jpg', 'portfolio-iweek-1000.jpg', 'portfolio-galavante.jpg', 'portfolio-ypm-cover.jpg', 'portfolio-fb2007.jpg', 'portfolio-mainscreen.jpg'),
    'alt_title' => array('pronq by HP','Car And Driver Model Super Page', 'Car And Driver Content Hub', 'Car And Driver Menu Navigation', 'Wealth Management Resource Network', 'Information Week 1000, 500, and 50', 'The Galavante Group', 'Yoga Practice Manual', 'Merrill Lynch Factbook', 'Mainscreen Print Procurement Database System'),
    'thumbnail_image' => array('pt-pronq-image.jpg','pt-candd-msp-image.jpg', 'pt-candd-contenthub-image.jpg', 'pt-candd-menu-nav-image.jpg', 'pt-wm-resource-network.jpg', 'pt-iweek-1000.jpg', 'pt-galavante.jpg', 'pt-ypm.jpg', 'pt-fb2007.jpg', 'pt-mainscreen.jpg'),
    'which_node' => array('pronq-hp','car-and-driver-model-super-page', 'car-and-driver-content-hub', 'car-and-drivers-menu-navigation', 'wealth-management-resource-network', 'industry-week-100-500-and-50-rankings', 'galavante-group', 'yoga-practice-manual', 'merrill-lynch-factbook', 'mainscreen-filemaker-pro'),
    'caption_title' => array('pronq by HP Website Project','Car And Driver Model Super Page Website Project', 'Car And Driver Content Hub Website Project', 'Car And Driver Menu Navigation Website Project', 'Wealth Management Resource Network Website Project', 'Industry Week 100, 500, and 50 Rankings Website Project', 'The Galavante Group Website Project', 'Yoga Practice Manual', 'Merrill Lynch Factbook', 'Merrill Lynch Mainscreen Print Procurement database solution'),
    'project_type' => array('Web', 'Web', 'Web', 'Web', 'Web', 'Web', 'Web', 'Print', 'Print', 'Print'),

  )); 
}

/**
 * Implements hook_theme().
 */
function full_portfolio_theme() {
  $module_path = drupal_get_path('module', 'full_portfolio');
  $base = array(
    'path' => "$module_path/theme",
  );
  return array(
    'full_portfolio' => $base + array(
      'template' => 'full-portfolio-block',
      'variables' => array(
        'keys' => NULL,
        'class_and_data_type' => NULL,
        'data_id' => NULL,
        'portfolio_image' => NULL,
        'alt_title' => NULL,
        'thumbnail_image' => NULL,
        'which_node' => NULL,
        'caption_title' => NULL,
        'project_type' => NULL,
      ),
    ),
  );
}
