<?php

/**
 * @file
 * A content block for the Header Social links.
 */

/**
 * Implements hook_init().
 */
function header_social_links_init() {

  /**
   * Add jquery.tipsy.js file for header social icons
   */
  if (theme_get_setting('header_tooltip_js','simplecorp')) {
  
    drupal_add_js(drupal_get_path('theme', 'simplecorp') . '/js/plugins/jquery.tipsy.js');

    drupal_add_js(drupal_get_path('module', 'header_social_links') . '/js/header_social_links.js');

  }
}		

/**
 * Implements hook_block_info().
 */
function header_social_links_block_info() {
  $blocks = array();
  
  $blocks['header_social_links'] = array(
    'info' => t('Custom Modules / Header Social Links'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function header_social_links_block_view($delta = '') {
  // Create an empty block.
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    
    case 'header_social_links':
      $block['subject'] = t('');
      $block['content'] = header_social_links();
      break;
  }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function header_social_links() {
  return theme('header_social_links', array()); 
}

/**
 * Implements hook_theme().
 */
function header_social_links_theme() {
  $module_path = drupal_get_path('module', 'header_social_links');
  $base = array(
    'path' => "$module_path/theme",
  );
  return array(
    'header_social_links' => $base + array(
      'template' => 'header-social-links-block',
    ),
  );
}