<?php

/**
 * @file
 * A content block for the Header Social links.
 */

/**
 * Implements hook_block_info().
 */
function header_social_links_block_info() {
  $blocks = array();
  
  $blocks['bottom_content'] = array(
    'info' => t('Custom Modules / Header Social LInks'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function header_social_links_block_view($delta = '') {
  // Create an empty block.
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    
    case 'bottom_content':
      $block['subject'] = t('');
      $block['content'] = header_social_links();
      break;
  }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function header_social_links() {
  return '
  <!-- #socialIcons -->
  <div id="social-icons" class="clearfix">
    <ul id="social-links">
      <li class="facebook-link"><a href="https://www.facebook.com/eric.sod" class="facebook" id="social-01" title="Join Me on Facebook!">Facebook</a></li>
      <li class="twitter-link"><a href="https://twitter.com/EricSod" class="twitter" id="social-02" title="Follow Me on Twitter">Twitter</a></li>
      <li class="google-link"><a href="#" id="social-03" title="Google" class="google">Google</a></li>
      <li class="dribbble-link"><a href="http://dribbble.com/EricSod" id="social-04" title="Dribble" class="dribbble">Dribble</a></li>
      <li class="vimeo-link"><a href="https://vimeo.com/user10386020" id="social-05" title="Vimeo" class="vimeo">Vimeo</a></li>
      <li class="skype-link"><a href="http://www.skype.com/en/" id="social-06" title="Skype" class="skype">Skype</a></li>
      <li class="linkedin-link"><a href="http://www.linkedin.com/in/ericsod" id="social-07" title="Linkedin" class="linkedin">Linkedin</a></li>
      <li class="pinterest-link"><a href="#" id="social-09" title="Pinterest" class="pinterest">Pinterest</a></li>
      <li class="rss-link"><a href="#" id="social-08" title="RSS" class="rss">RSS Feeds</a></li>
    </ul>
  </div>
  <!-- EOF: #socialIcons -->
'
  ;
}
