<?php

/**
 * @file
 * A content block for the bottom of the home page.
 */

/**
 * Implements hook_block_info().
 */
function bottom_content_block_info() {
  $blocks = array();
  
  $blocks['bottom_content'] = array(
    'info' => t('Custom Modules / Bottom Content'),
  );
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function bottom_content_block_view($delta = '') {
  // Create an empty block.
  $block = array(
    'subject' => '',
    'content' => '',
  );

  switch ($delta) {
    
    case 'bottom_content':
      $block['subject'] = t('');
      $block['content'] = bottom_content();
      break;
  }
  
  return $block;
}

/**
 * custom html block
 * @return string
 */
function bottom_content() {
  return '
    <h3>Featured Work</h3>
      <ul id="projects-carousel" class="loading">
      
      <!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-pronq.jpg" alt="pronq by HP" title="pronq by HP" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-pronq-image.jpg" alt="pronq by HP" width="220"  class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/14" title="title">pronq by HP Website Project</a></p>
                <span>Web</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' .

      '<!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-candd-msp.jpg" alt="Car And Driver Model Super Page" title="Car And Driver Model Super Page" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-candd-msp-image.jpg" alt="Car And Driver Model Super Page" title="Car And Driver Model Super Page" width="220" class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/15" title="title"> Car And Driver Model Super Page Website Project</a></p>
                <span>Web</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' . 
    
      '<!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-candd-contenthub.jpg" alt="Car And Driver Content Hub" title="Car And Driver Content Hub" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-candd-contenthub-image.jpg" alt="Car And Driver Content Hub" title="Car And Driver Content Hub" width="220" class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/21" title="title">Car And Driver Content Hub Website Project</a></p>
                <span>Web</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' . 
    
    
      '<!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-candd-menu-nav.jpg" title="Car And Driver Menu Navigation" alt="Car And Driver Menu Navigation" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-candd-menu-nav-image.jpg" title="Car And Driver Menu Navigation" alt="Car And Driver Menu Navigation" width="220" class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/17" title="title">Car And Driver Menu Navigation Website Project</a></p>
                <span>Web</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' . 
    
      '<!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-wm-resource-network.jpg" title="Wealth Management Resource Network" alt="Wealth Management Resource Network" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-wm-resource-network.jpg" title="Wealth Management Resource Network" alt="Wealth Management Resource Network" width="220" class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/18" title="title">Wealth Management Resource Network Website Project</a></p>
                <span>Web</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' . 
    
      '<!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-iweek-1000.jpg" title="Information Week 1000, 500, and 50" alt="Information Week 1000, 500, and 50" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-iweek-1000.jpg" title="Industry Week 100, 500, and 50 Rankings" alt="Industry Week 100, 500, and 50 Rankings" width="220" class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/22" title="title">Industry Week 100, 500, and 50 Rankings Website Project</a></p>
                <span>Web</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' . 
        
      '<!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-galavante.jpg" alt="The Galavante Group" title="The Galavante Group" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-galavante.jpg" alt="The Galavante Group" title="The Galavante Group" width="220" class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/23" title="title">The Galavante Group Website Project</a></p>
                <span>Web</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' . 
    
      '<!-- PROJECT ITEM STARTS -->
        <li>
          <div class="item-content">
            <div class="link-holder">
              <div class="portfolio-item-holder">
                <div class="portfolio-item-hover-content">
                  <a href="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/portfolio-ypm-cover.jpg" alt="Yoga Practice Manual" title="Yoga Practice Manual" data-rel="prettyPhoto" class="zoom">View Image</a>
                  <img src="' . base_path() . drupal_get_path('theme', 'simplecorp') . '/images/sampleimages/pt-ypm.jpg" alt="Yoga Practice Manual" title="Yoga Practice Manual" width="220" class="portfolio-img" />
                  <div class="hover-options"></div>
                </div>
              </div>
              <div class="description"> 
                <p><a href="' . base_path() . 'node/16" title="title">Yoga Practice Manual</a></p>
                <span>Print</span>
              </div>
            </div>
          </div>
        </li>
        <!-- PROJECT ITEM ENDS -->' . 
    
      '</ul>
    <!-- // optional "view full portfolio" button on homepage featured projects -->
    <a href="' . base_path() . 'node/13" class="colored" title="portofolio">View full portofolio</a>'
  ;
}
