<?php
// $Id$

/**
 * @file
 * Implement geshi-plugin for module wysiwyg.
 */

/**
* Implementes hook_menu().
*/
function wysiwyg_geshi_plugin_menu() {
  $items = array();
  $items['wysiwyg_geshi_plugin/dialog'] = array(
    'page callback' => 'wysiwyg_geshi_plugin_dialog',
    'page arguments' => array(),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function wysiwyg_geshi_plugin_dialog() {
?>
<html>
<head>
  <style type="text/css">
    body {background:#FFF}
    * {font-size:12px;color:#000;font-family:Tahoma}
    td {vertical-align:top; padding: 1px;}
	td.rtool label {white-space:nowrap;font-weight:bold}
	label {cursor:pointer;outline:0}
  </style>
  <script type="text/javascript">
  function WysiwygPluginGeshiClose() {
    window.parent.WysiwygPluginGeshiClose();
  }
  function WysiwygPluginGeshiCancel() {
    document.getElementById('sample').style.display='none';
    document.getElementById('fForm').style.display='block';
  }
  function WysiwygPluginGeshiPaste(content) {
    window.parent.Drupal.wysiwyg.instances[window.parent.WysiwygPluginGeshiInstanceId].insert(content);
    WysiwygPluginGeshiClose();
  }
  </script>
  </head>
  <?php
  $_post_code = $result = '';
  $_post_language = 'cpp';
   
  if (is_file('sites/all/libraries/geshi/geshi.php')) {
		require_once('sites/all/libraries/geshi/geshi.php');
  }

  $langs = &drupal_static(__FUNCTION__);
  if (!isset($langs)) {
		$langs = array();
    $geshi_library = libraries_load('geshi');
    $lang_dir = $geshi_library['library path'] . '/geshi';
		if (is_dir($lang_dir)) {
			$handle = opendir($lang_dir);
			if ($handle) {
			while (false !== ($file = readdir($handle))) {
				if ($file!='.' && $file!='..') {
				require($lang_dir . '/' . $file);
				if (isset($language_data)) {
					$code = str_replace('.php', '', $file);
					if (variable_get('geshifilter_language_enabled_' . $code, FALSE)) {
						$langs[$code] = $language_data['LANG_NAME'];
					}
				}
				unset($language_data);
				}
			}
			closedir($handle);
			}
		}
		asort($langs);
	}
  
  $options = array();
  $options['enable_line_numbers'] = GESHI_FANCY_LINE_NUMBERS;
	$options['linenumbers_start'] = 1;
	$options['fancy'] = 10;
	$options['title'] = '';
  
  if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $_post_language = isset($_POST['language']) ? preg_replace('/[^a-z0-9]/', '', $_POST['language']) : '';
    $_post_code = isset($_POST['code']) ? $_POST['code'] : '';
    
		$options['enable_line_numbers'] = isset($_POST['options']['enable_line_numbers']) ? preg_replace('/[^0-9]/', '', $_POST['options']['enable_line_numbers']) : $options['enable_line_numbers'];
		$options['title'] = isset($_POST['options']['title']) ? check_plain($_POST['options']['title']) : $options['title'];	
		$options['linenumbers_start'] = isset($_POST['options']['linenumbers_start']) ? preg_replace('/[^0-9]/', '', $_POST['options']['linenumbers_start']) : $options['linenumbers_start'];
		$options['fancy'] = isset($_POST['options']['fancy']) ? preg_replace('/[^0-9]/', '', $_POST['options']['fancy']) : $options['fancy'];
		
		$geshi = new Geshi($_post_code, $_post_language);
		$geshi->set_header_type(GESHI_HEADER_DIV);
		$geshi->start_line_numbers_at($options['linenumbers_start']);
		if ($options['enable_line_numbers'] != GESHI_FANCY_LINE_NUMBERS) {
			$geshi->enable_line_numbers($options['enable_line_numbers']);
		} else {
			$geshi->enable_line_numbers(GESHI_FANCY_LINE_NUMBERS, $options['fancy']);
		}
		$geshi->enable_keyword_links(true);
		$geshi->set_overall_class('codeblock');
		$geshi->set_tab_width('4');
		$geshi->set_encoding('utf-8');        
		$geshi->enable_classes(false);
		$result = $geshi->parse_code();
				
    $_post_code = htmlspecialchars($_post_code, ENT_QUOTES, 'UTF-8');
		
    ?>
    <div id="sample">
      <div style="padding:5px;background:#EFFFEF;margin-bottom:10px;height:330px;overflow:auto"><?php echo $result?></div>
			<div style="display: none;" id="result_insert"><pre
<?php
if ($options['enable_line_numbers'] == GESHI_NO_LINE_NUMBERS) {
	echo " linenumbers=\"off\" ";
} else {
	if ($options['linenumbers_start'] != '') {
		echo " start=\"" . $options['linenumbers_start'] . "\" ";
	}
	if ($options['enable_line_numbers'] == GESHI_FANCY_LINE_NUMBERS) {
		echo " linenumbers=\"fancy\" ";
		if ($options['fancy'] != '') {
			echo " fancy=\"" . $options['fancy'] . "\" ";
		}
	} else {
		echo " linenumbers=\"normal\" ";		
	}
}
if (trim($_post_language)) {
	echo " type=\"" . $_post_language . "\" ";
}
if (trim($options['title'])) {
	echo " title=\"" . $options['title'] . "\" ";
}
?>><?php echo $_post_code?></pre></div>
      <div style="float:left"><input type="button" onclick="WysiwygPluginGeshiPaste(document.getElementById('result_insert').innerHTML)" value="Send to editor!" /></div>
      <div style="float:right"><input type="button" onclick="WysiwygPluginGeshiCancel();" value="Cancel" /></div>
      <div style="clear:both"></div>
    </div>
  <?php
  }
  ?>
  <form id="fForm" action="index.php?q=wysiwyg_geshi_plugin/dialog" method="post" <?php echo strlen($result)?'style="display:none"':''?>>
  <?php
  if (!count($langs)) :
  ?>
    <div style="font-weight:bold;color:#C00;padding:10px">
      <p>Not found GeSHi library in "sites/all/libraries/geshi/"</p>
      <p>Must be next structure:</p>
      <p>
        - sites/all/libraries/geshi/geshi.php<br />
        - sites/all/libraries/geshi/geshi/*.php
      </p>
      <p>Your can download library from <a href="http://qbnz.com/highlighter/" target="_blank">GeSHi - Generic Syntax Highlighter</a> and place "geshi" folder from archive to "sites/all/libraries/"</p>
    </div>
    <input type="button" onclick="WysiwygPluginGeshiClose();" value="Close" />
  <?php else: ?>
    <table cellspacing="0" cellpadding="10" width="100%" style="height:330px; cellpadding=0; cellspacing=0">
			<tr>
        <td class="rtool">
					<div style="width:100%">
						<label for="options_title">Title:</label>
						<input style="width:100%" type="input" id="options_title" name="options[title]" value="<?php echo $options['title']; ?>" />
					</div>
					<div style="width:100%">
					<label for="options_language">Language:</label>
					<select id="options_language" name="language" style="width:100%">
							<?php	foreach ($langs as $code => $title) {
									echo '<option value="' . $code . '" ' . ($code == $_post_language?'selected="selected"':'') . '>' . check_plain($title) . '</option>';
							} ?>
					</select>
					</div>
        </td>
        <td class="rtool">
					<div>
						<label for="options_enable_line_numbers">Line numbers</label><br />
						<select id="options_enable_line_numbers" name="options[enable_line_numbers]">
							<option value="<?php echo GESHI_NO_LINE_NUMBERS?>" <?php echo ($options['enable_line_numbers'] == GESHI_NO_LINE_NUMBERS?'selected="selected"':'')?>>No line numbers</option>
							<option value="<?php echo GESHI_FANCY_LINE_NUMBERS?>" <?php echo ($options['enable_line_numbers'] == GESHI_FANCY_LINE_NUMBERS?'selected="selected"':'')?>>Fancy line numbers</option>
							<option value="<?php echo GESHI_NORMAL_LINE_NUMBERS?>" <?php echo ($options['enable_line_numbers'] == GESHI_NORMAL_LINE_NUMBERS?'selected="selected"':'')?>>Normal line numbers</option>
						</select>
					</div>
					<div style="padding-top:5px">
						<label for="options_linenumbers_start">Start line number</label>
						<input type="input" id="options_linenumbers_start" name="options[linenumbers_start]" value="<?php echo $options['linenumbers_start']; ?>" />
					</div>
					<div style="padding-top:5px">
						<label for="options_fancy">Fancy line number</label>
						<input type="input" id="options_fancy" name="options[fancy]" value="<?php echo $options['fancy']; ?>" />
					</div>
				</td>
			</tr>
			<tr style="height:310px;">
        <td colspan="2"><strong>Code:</strong><br />
          <textarea name="code" style="resize: none; height:310px;width:100%"><?php echo check_plain($_post_code)?></textarea>
        </td>
      </tr>
    </table>
    <div style="float:left"><input type="submit" value="Highlight it!" /></div>
    <div style="float:right"><input type="button" onclick="WysiwygPluginGeshiClose();" value="Close" /></div>
    <div style="clear:both"></div>
  </form>
  
  <?php endif; ?>
  </body>
  </html>
  <?php
}

function wysiwyg_geshi_plugin_wysiwyg_include_directory($type) {
  if ($type == 'plugins') {
    return $type;
  }
}